### ISSUE TITLE
Reconsider window.addEventistener() behavior

### ISSUE THREAD

**Issue by nnemkin** [Alhadis/Fix-IE#2]
All `window.addEventistener()` calls are redirected to `document` [here](https://github.com/Alhadis/Fix-IE/blob/master/src/IE8-addEventListener.js#L54).
I've no idea why, but it does break valid code like:
```javascript
window.addEventListener('scroll', scroll);
window.addEventListener('resize', update);
```
Except for this bit, your shims work really well.
:thumbsup:

**Comment by Alhadis** [comment]
Thank you! :)))

As you probably know, IE8 lacks support for `window.addEventListener`... but `window.attachEvent` isn't a seamless replacement. Specifically, its event bubbling is flawed, and certain events dispatched on the `window` global aren't communicated to the `document`.

I wasn't aware there were issues with this; could you please elaborate on how this is breaking? Perhaps provide me with a few stack-traces?

**Comment by nnemkin** [comment]
There are no stack traces, the events simply don't fire. Small code example that handles `onload`, `onscroll` and `onresize`:

```javascript
  function ready(fn) {
    if (document.readyState == 'complete') {
      fn();
    }
    else {
      window.addEventListener('load', fn);
    }
  }

  ready(function() {
    window.addEventListener('scroll', function() {
        console.log('scroll');
    });
    window.addEventListener('resize', function() {
        console.log('resize');
    });
  });
```

Those events are window object events, document object doesn't fire them, hence the breakage.

Honestly, I'm not familiar with IE8 quirks. If redirection is important for other use cases, maybe you can skip it if the event is a window-only event?

UPD: `onscroll` is not window-only, but scroll plugins (my use case) usually need the window version of it.

**Comment by Alhadis** [comment]
I'm a little too busy right now to look at this closer (will investigate later), but I vaguely recall IE8 may have used a different mechanism for monitoring page-scrolling. In the typically broken fashion of Internet Explorer, the event was somewhere else (possibly the `body`, or a non-standard interface).

My memory of that's become faded over the years, though, but it could be worth investigating if it leads you to an interim solution. :)

It probably won't take me long to get back to this, I just hate knowing something I've written is broken and affecting users.

**Comment by nnemkin** [comment]
Oh, don't worry about it. I've simply replaced `document` with `window` [in those two lines](https://github.com/Alhadis/Fix-IE/blob/master/src/IE8-addEventListener.js#L55-L56) and my vanilla JS scroll plugins written for IE10+ work perfectly in IE8.

So in fact, IE8 window scroll works just like any other browser, and for scroll and load events, `attachEvent` is equivalent to `addEventListener`.

**Comment by Alhadis** [comment]
Wait, it's actually possible IE doesn't dispatch *any* events when scrolling, period. I recall `scrollTop` not existing in Explorer prior to IE9, which might explain why you're not witnessing any response from the handlers.

**Comment by nnemkin** [comment]
IE8 does dispatch onscroll just fine, and `scrollTop` (aka `scrollY`) is [included in your shims](https://github.com/Alhadis/Fix-IE/blob/master/src/IE8-offsets.js)!
_It just works_ as long as you don't redirect `window.addEventHandler` to `document.attachEvent`.

**Comment by Alhadis** [comment]
Erh... yeah, you're right. I really shouldn't think in more than 10 headspaces... sorry (`scrollY` might've been what I was recollecting inaccurately).

Rerouting was a solution for a different problem; it may have been getting `click` events to bubble. I was developing [this](https://github.com/Alhadis/Accordion) around the time these shims were published on their own, and it's possible the accordion folds weren't opening on IE8 when I tested.

Either way, it was a kludgey solution which certainly needs revising; thanks for bringing it to my attention. :)
